### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by mwilcox12015** [IBM-Bluemix-Docs/CDN#23]
Link on this page https://cloud.ibm.com/docs/infrastructure/CDN?topic=CDN-getting-started to 'Heres a tutorial'  is a broken link   ie https://cloud.ibm.com/docs/infrastructure/CDN?topic=CDN-getting-started

**Comment by bali2016** [comment]
> 
> 
> Link on this page https://cloud.ibm.com/docs/infrastructure/CDN?topic=CDN-getting-started to 'Heres a tutorial' is a broken link ie https://cloud.ibm.com/docs/infrastructure/CDN?topic=CDN-getting-started

@mwilcox12015 Thanks for the information, and we will do the update.

**Comment by bali2016** [comment]
The broken link has been fixed and we can close this issue now.
